print("What do you call a bear with no teeth?")
input("")
print("A gummy bear!!!!")
input("")
print("Why did the bicycle fall over?")
input("")
print("Because it was two-tired!")
input("")
print("How does a penguin build a house?")
input("")
print("Igloos it together!!!!!!!!")
input("")
print("What do you call a person with no body or nose?")
input("")
print("Nobody nose!")