print("Hi my name is Campbell")
name = input("What is your name?")
print(f"Nice to meet you {name}!")
print("Ready to talk about your dream vacation?")
input("")
place = input("Ok,what would be your dream place to take a vacation")
print(f"{place} is a very cool vacation spot!")
weather = input("If you went on this trip what weather would you want it to be?")
input("")
print(f"So far your dream vacation would be in {place} and the weather would be {weather}")
print("Lets find a little bit more about your dream vacation, click enter to continue.")
stay = input(f"Where would you want to stay in {place}? ex.by the beach, in the city,etc.")
