print("Hi my name is Campbell")
name = input("What is your name?")
print(f"Nice to meet you {name}!")
print("Ready to talk about your dream vacation?")
input("")
place = input("Ok,what would be your dream place to take a vacation?")
print(f"{place} is a very cool vacation spot!")
weather = input("If you went on this trip what weather would you want it to be?")
input("")
print(f"So far your dream vacation would be in {place} and the weather would be {weather}")
print("Lets find a little bit more about your dream vacation, click enter to continue.")
input("")
stay = input(f"Where would you want to stay in {place}? ex.by the beach, in the city,etc.")
who = input(f"Who would you want to travel with? Yourself,friends, or family?")
excited = input(f"What would you most be excited to do in {place}? Try a certain food, see a specific site, do a fun activity?")
input("")
print(f"Ok after our chat I learned that your dream vacation would be to {place}! You would want the weather to be {weather} while you're there and you would want to travel with {who}. While you're there you would want to stay {stay} and go {excited}")
print("Thanks for talking about your dream vacation with me!")
print(f"Have a nice rest of your day {name}")